### ISSUE TITLE
python_plugin: No module named scripts.lib_pipeline

### ISSUE THREAD

**Issue by mknapp55** [lofar-astron/PiLL#27]
Error at step selfcal-filter_model:
```
4128 2017-07-06 15:06:57 DEBUG   node.ip-100-64-109-221.python_plugin: infile            = /data/t1data/lba/L402127/L402127_SB000_uv.dppp.MS
4129 2017-07-06 15:06:57 DEBUG   node.ip-100-64-109-221.python_plugin: executable        = /lofsoft/PiLL/scripts/filter_model.py
4130 2017-07-06 15:06:57 DEBUG   node.ip-100-64-109-221.python_plugin: working directory = /data/t1data/lba/working_L402125/pipeline
4131 2017-07-06 15:06:57 DEBUG   node.ip-100-64-109-221.python_plugin: arguments         = []
4132 2017-07-06 15:06:57 DEBUG   node.ip-100-64-109-221.python_plugin: arg dictionary    = {'maskname': '/data/t1data/lba/working_L402125/pipeline/L402127_SB000_uv.dppp_     127330D8At_77MHz_TC1.selfcal-image_high1-MFS-image.selfcal-mask_high', 'skymodel_cut': '/data/t1data/lba/working_L402125/pipeline/L402127_SB000_uv.dppp.selfcal-filt     er_model', 'skymodel': '/data/t1data/lba/working_L402125/pipeline/L402127_SB000_uv.dppp_127330D8At_77MHz_TC1.selfcal-image_high2-sources.txt', 'ms': '/data/t1data/l     ba/L402127/L402127_SB000_uv.dppp.MS'}
4133 2017-07-06 15:06:57 DEBUG   node.ip-100-64-109-221.python_plugin: environment       = {'OMP_NUM_THREADS': '8', 'PATH': '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin     :/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin', 'LOFARROOT': '/usr', 'PYTHONPATH': '/usr/lib/python2.7/dist-packages:/data/scripts/'     }
4134 2017-07-06 15:06:57 INFO    node.ip-100-64-109-221.python_plugin: Processing /data/t1data/lba/L402127/L402127_SB000_uv.dppp.MS
4135 2017-07-06 15:06:57 DEBUG   genericpipeline.executable_args: Results for job 0 submitted by ('127.0.0.1', 37830)
4136 2017-07-06 15:06:57 ERROR   node.ip-100-64-109-221.python_plugin: No module named scripts.lib_pipeline
```

**Comment by adrabent** [comment]
From which directory do you start the pipeline?

**Comment by mknapp55** [comment]
I set the local_directory explicitly in the parset to the PiLL directory.  I run the pipeline via the LBA_pipeline.py script in that directory with full paths to that executable, the parset, and the working directory.

**Comment by adrabent** [comment]
Hmm, so I have to change the script in that way that it is able to import a module given the full path.

**Comment by mknapp55** [comment]
FWIW, I use the full paths because I'm running from a Singularity container via `exec`.  I suppose I could go into the Singularity shell and cd to the PiLL directory and run from there, but that's not ideal.  I sometimes bypass the `LBA_pipeline.py` script and use `genericpipeline.py` directly if I need to customize the `pipeline.cfg`, in which case I usually run from the working directory or the data directory with full paths and explicit `local_directory`.

**Comment by adrabent** [comment]
Could you please test, whether my changes work? I have no data set at this stage currently to test it.

**Comment by mknapp55** [comment]
Got rid of the old error, but now it can't find global name `get_phase_centre`:
```
2017-07-06 21:13:47 DEBUG   node.ip-100-64-109-221.python_plugin: infile            = /data/t1data/lba/L402127/L402127_SB000_uv.dppp.MS
2017-07-06 21:13:47 DEBUG   node.ip-100-64-109-221.python_plugin: executable        = /lofsoft/PiLL/scripts_mk/filter_model.py
2017-07-06 21:13:47 DEBUG   node.ip-100-64-109-221.python_plugin: working directory = /data/t1data/lba/working_L402125/pipeline
2017-07-06 21:13:47 DEBUG   node.ip-100-64-109-221.python_plugin: arguments         = []
2017-07-06 21:13:47 DEBUG   node.ip-100-64-109-221.python_plugin: arg dictionary    = {'maskname': '/data/t1data/lba/working_L402125/pipeline/L402127_SB000_uv.dppp_127330D8At_77MHz_TC1.selfcal-image_high1-MFS-image.selfcal-mask_high', 'skymodel_cut': '/data/t1data/lba/working_L402125/pipeline/L402127_SB000_uv.dppp.selfcal-filter_model', 'skymodel': '/data/t1data/lba/working_L402125/pipeline/L402127_SB000_uv.dppp_127330D8At_77MHz_TC1.selfcal-image_high2-sources.txt', 'ms': '/data/t1data/lba/L402127/L402127_SB000_uv.dppp.MS', 'scripts': '/lofsoft/PiLL/scripts_mk'}
2017-07-06 21:13:47 DEBUG   node.ip-100-64-109-221.python_plugin: environment       = {'OMP_NUM_THREADS': '8', 'PATH': '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin', 'LOFARROOT': '/usr', 'PYTHONPATH': '/usr/lib/python2.7/dist-packages:/data/scripts/'}
2017-07-06 21:13:47 INFO    node.ip-100-64-109-221.python_plugin: Processing /data/t1data/lba/L402127/L402127_SB000_uv.dppp.MS
2017-07-06 21:13:47 ERROR   node.ip-100-64-109-221.python_plugin: global name 'get_phase_centre' is not defined
```
I edited the script myself to add `scripts` as an argument to `main()` in `filter_model.py` (that's why the path is to `scripts_mk`), but ended up with this error anyway.

**Comment by mknapp55** [comment]
`get_phase_centre()` is in `lib_pipeline_ms`.  I imported this module too, but I got the same error.  I'm out of ideas - I'll leave it to you :)

**Comment by adrabent** [comment]
Do you get the same error when you run the script outside the pipeline? You have to provide the scripts directory hardcoded.

**Comment by mknapp55** [comment]
When I run it outside the pipeline, it does seem to pick up the path.  See below.  I've also attached the modified version that I ran (which has 'scripts' in argparse).
```
ubuntu@ip-100-64-109-221:/data/t1data/lba$ python /lofsoft/PiLL/scripts_mk/filter_model.py --scripts /lofsoft/PiLL/scripts_mk --mask /data/t1data/lba/working_L402125/pipeline/L402127_SB000_uv.dppp_127330D8At_77MHz_TC1.selfcal-image_high1-MFS-image.selfcal-mask_high --ms /data/t1data/lba/L402127/L402127_SB000_uv.dppp.MS --output /data/t1data/lba/working_L402125/pipeline/L402127_SB000_uv.dppp.selfcal-filter_model --skymodel /data/t1data/lba/working_L402125/pipeline/L402127_SB000_uv.dppp_127330D8At_77MHz_TC1.selfcal-image_high2-sources.txt 
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/lofsoft/PiLL/scripts_mk/filter_model.py", line 44, in <module>
    from lib_pipeline import *
  File "/lofsoft/PiLL/scripts_mk/lib_pipeline.py", line 5, in <module>
    from lofar import bdsm
  File "/usr/lib/python2.7/dist-packages/lofar/bdsm/__init__.py", line 21, in <module>
    from islands import Op_islands
  File "/usr/lib/python2.7/dist-packages/lofar/bdsm/islands.py", line 19, in <module>
    from astropy.io import fits as pyfits
  File "/usr/lib/python2.7/dist-packages/astropy/__init__.py", line 112, in <module>
    _check_numpy()
  File "/usr/lib/python2.7/dist-packages/astropy/__init__.py", line 100, in _check_numpy
    from .utils import minversion
  File "/usr/lib/python2.7/dist-packages/astropy/utils/__init__.py", line 18, in <module>
    from .misc import *
  File "/usr/lib/python2.7/dist-packages/astropy/utils/misc.py", line 28, in <module>
    from ..utils.compat.odict import OrderedDict
  File "/usr/lib/python2.7/dist-packages/astropy/utils/compat/__init__.py", line 14, in <module>
    from .numpycompat import *
  File "/usr/lib/python2.7/dist-packages/astropy/utils/compat/numpycompat.py", line 18, in <module>
    NUMPY_LT_1_6_1 = not minversion('numpy', '1.6.1')
  File "/usr/lib/python2.7/dist-packages/astropy/utils/introspection.py", line 154, in minversion
    from pkg_resources import parse_version
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 626, in _build_master
    ws = cls()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 619, in __init__
    self.add_entry(entry)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 673, in add_entry
    self.entry_keys.setdefault(entry, [])
TypeError: unhashable type: 'list'
```
[filter_model_mk.txt](https://github.com/lofar-astron/PiLL/files/1130823/filter_model_mk.txt)

**Comment by mknapp55** [comment]
I toyed with this problem a bit more.  I tried running the pipeline from inside the PiLL folder using LBA_pipeline.py - that didn't work (same error that get_phase_centre() couldn't be found).  I tried to run the import command from ipython, and that worked.  There's some issue with one of the modules in lib_pipeline, but lib_pipeline_ms imported fine and get_phase_center() worked.  I reverted the script back to your original and ran the pipeline - it said it couldn't find scripts.lib_pipeline_ms.  I don't know why, since I could do that manually from the same directory.  
Sorry I don't have a solution, but maybe some of this will help.

**Comment by mknapp55** [comment]
```
2017-07-30 04:52:03 INFO    genericpipeline.executable_args: Starting /lofsoft/PiLL/scripts/filter_model.py run
Reading configuration file: /data/scripts/working_L402756/pipeline.cfg
Reading task definition file(s): /usr/share/pipeline/tasks.cfg
2017-07-30 04:52:03 DEBUG   genericpipeline.executable_args: Pipeline start time: 2017-07-30T04:51:52
2017-07-30 04:52:03 INFO    genericpipeline.executable_args: Limiting to 16 simultaneous jobs/node
2017-07-30 04:52:03 DEBUG   genericpipeline.executable_args: Job dispatcher at 128.149.112.159:46696
2017-07-30 04:52:03 INFO    genericpipeline.executable_args: ********************** Remote method is local
2017-07-30 04:52:03 INFO    genericpipeline.executable_args: Waiting for compute threads...
2017-07-30 04:52:03 INFO    genericpipeline.executable_args: Subprocess starting: /bin/sh -c python /usr/lib/python2.7/dist-packages/lofarpipe/recipes/nodes/python_plugi
n.py 0 128.149.112.159 46696 (['/bin/sh', '-c', 'python /usr/lib/python2.7/dist-packages/lofarpipe/recipes/nodes/python_plugin.py 0 128.149.112.159 46696'])
2017-07-30 04:52:03 WARNING genericpipeline.executable_args: /usr/lib/python2.7/dist-packages/lofarpipe/support/utilities.pyc : Using default subprocess module!
2017-07-30 04:52:03 DEBUG   genericpipeline.executable_args: Request for job 0 from ('128.149.112.159', 40482)
2017-07-30 04:52:04 WARNING genericpipeline.executable_args: /lofsoft/PiLL/scripts/filter_model.py:5: SyntaxWarning: import * only allowed at module level
2017-07-30 04:52:04 WARNING genericpipeline.executable_args:   def main(ms,skymodel,maskname,skymodel_cut,scripts,keep_in_beam=True):
2017-07-30 04:52:03 DEBUG   node.jvla.jpl.nasa.gov.python_plugin: infile            = /data/L402758/L402758_SB000_uv.dppp.MS
2017-07-30 04:52:04 DEBUG   node.jvla.jpl.nasa.gov.python_plugin: executable        = /lofsoft/PiLL/scripts/filter_model.py
2017-07-30 04:52:04 DEBUG   node.jvla.jpl.nasa.gov.python_plugin: working directory = /data/scripts/working_L402756/LBA_pipeline_L402756
2017-07-30 04:52:04 DEBUG   node.jvla.jpl.nasa.gov.python_plugin: arguments         = []
2017-07-30 04:52:04 DEBUG   node.jvla.jpl.nasa.gov.python_plugin: arg dictionary    = {'maskname': '/data/scripts/working_L402756/LBA_pipeline_L402756/L402758_SB000_uv.d
ppp_1273828E3t_77MHz_TC5.selfcal-image_high1-MFS-image.selfcal-mask_high', 'skymodel_cut': '/data/scripts/working_L402756/LBA_pipeline_L402756/L402758_SB000_uv.dppp.self
cal-filter_model', 'skymodel': '/data/scripts/working_L402756/LBA_pipeline_L402756/L402758_SB000_uv.dppp_1273828E3t_77MHz_TC5.selfcal-image_high2-sources.txt', 'ms': '/d
ata/L402758/L402758_SB000_uv.dppp.MS', 'scripts': '/lofsoft/PiLL/scripts'}
2017-07-30 04:52:04 DEBUG   node.jvla.jpl.nasa.gov.python_plugin: environment       = {'OMP_NUM_THREADS': '8', 'PATH': '/usr/lib64/qt-3.3/bin:/usr/local/apache-maven-3.2.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/casapy:/home/mknapp/bin:/bin:/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin', 'LOFARROOT': '/usr', 'PYTHONPATH': '/usr/lib/python2.7/dist-packages:/data/scripts/', 'MODULEPATH': '/usr/share/Modules/modulefiles:/etc/modulefiles'}
2017-07-30 04:52:04 INFO    node.jvla.jpl.nasa.gov.python_plugin: Processing /data/L402758/L402758_SB000_uv.dppp.MS
2017-07-30 04:52:05 WARNING genericpipeline.executable_args: ERROR: No module named pyregion
2017-07-30 04:52:05 WARNING genericpipeline.executable_args: INFO: Total time 1.6561s; user time: 1.5248s; system time: 0.1650s
2017-07-30 04:52:05 WARNING genericpipeline.executable_args: DEBUG: Start time was 1501390324.0046s; end time was 1501390325.6609s
2017-07-30 04:52:05 ERROR   node.jvla.jpl.nasa.gov.python_plugin: No module named pyregion
2017-07-30 04:52:05 DEBUG   genericpipeline.executable_args: Results for job 0 submitted by ('128.149.112.159', 40486)
2017-07-30 04:52:05 INFO    node.jvla.jpl.nasa.gov.python_plugin: Total time 1.6561s; user time: 1.5248s; system time: 0.1650s
2017-07-30 04:52:05 DEBUG   node.jvla.jpl.nasa.gov.python_plugin: Start time was 1501390324.0046s; end time was 1501390325.6609s
2017-07-30 04:52:06 DEBUG   genericpipeline.executable_args: 
2017-07-30 04:52:06 WARNING genericpipeline.executable_args: 
2017-07-30 04:52:06 INFO    genericpipeline.executable_args: Subprocess completed with exit status 1: /bin/sh -c python /usr/lib/python2.7/dist-packages/lofarpipe/recipes/nodes/python_plugin.py 0 128.149.112.159 46696
2017-07-30 04:52:06 ERROR   genericpipeline.executable_args: Remote process python /usr/lib/python2.7/dist-packages/lofarpipe/recipes/nodes/python_plugin.py ['/data/L402758/L402758_SB000_uv.dppp.MS', '/lofsoft/PiLL/scripts/filter_model.py', [], {'maskname': '/data/scripts/working_L402756/LBA_pipeline_L402756/L402758_SB000_uv.dppp_1273828E3t_77MHz_TC5.selfcal-image_high1-MFS-image.selfcal-mask_high', 'skymodel_cut': '/data/scripts/working_L402756/LBA_pipeline_L402756/L402758_SB000_uv.dppp.selfcal-filter_model', 'ms': '/data/L402758/L402758_SB000_uv.dppp.MS', 'skymodel': '/data/scripts/working_L402756/LBA_pipeline_L402756/L402758_SB000_uv.dppp_1273828E3t_77MHz_TC5.selfcal-image_high2-sources.txt', 'scripts': '/lofsoft/PiLL/scripts'}, '/data/scripts/working_L402756/LBA_pipeline_L402756', False, {'args_format_option_argument': '=', 'args_format_option': '-', 'args_format': 'gnu', 'args_formatlongoption': '--', 'args_format_argument': ''}, {'OMP_NUM_THREADS': '8', 'PATH': '/usr/lib64/qt-3.3/bin:/usr/local/apache-maven-3.2.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/casapy:/home/mknapp/bin:/bin:/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin', 'LOFARROOT': '/usr', 'MODULEPATH': '/usr/share/Modules/modulefiles:/etc/modulefiles', 'PYTHONPATH': '/usr/lib/python2.7/dist-packages:/data/scripts/'}] failed on localhost
```

**Comment by mknapp55** [comment]
Whoops - I just realized `pyregion` is an external python package I need to install.  I've done that and I'm rerunning selfcal for one of my datasets.  I tried to resume from selfcal-filter_model (using existing statefile), but I guess something changed because I get the 'does not match saved state' error.

**Comment by mknapp55** [comment]
It seems to work now, though with a warning about import syntax (below).  I've encountered an error on the next step, but I'll make that a separate ticket.

```
2017-08-01 23:26:22 DEBUG   node.ip-100-64-109-221.python_plugin: infile            = /data/t1data/lba/L525880/L525880_SB000_uv.MS
2017-08-01 23:26:22 WARNING genericpipeline.executable_args: /lofsoft/PiLL/scripts/filter_model.py:5: SyntaxWarning: import * only allowed at module level
2017-08-01 23:26:22 DEBUG   node.ip-100-64-109-221.python_plugin: executable        = /lofsoft/PiLL/scripts/filter_model.py
2017-08-01 23:26:22 WARNING genericpipeline.executable_args:   def main(ms,skymodel,maskname,skymodel_cut,scripts,keep_in_beam=True):
2017-08-01 23:26:22 DEBUG   node.ip-100-64-109-221.python_plugin: working directory = /data/t1data/lba/working_L525878/pipeline
2017-08-01 23:26:22 DEBUG   node.ip-100-64-109-221.python_plugin: arguments         = []
2017-08-01 23:26:22 DEBUG   node.ip-100-64-109-221.python_plugin: arg dictionary    = {'maskname': '/data/t1data/lba/working_L525878/pipeline/L525880_SB000_uv_128888861t_77MHz_TC2.selfcal-image_high1-MFS-
image.selfcal-mask_high', 'skymodel_cut': '/data/t1data/lba/working_L525878/pipeline/L525880_SB000_uv.selfcal-filter_model', 'skymodel': '/data/t1data/lba/working_L525878/pipeline/L525880_SB000_uv_1288888
61t_77MHz_TC2.selfcal-image_high2-sources.txt', 'ms': '/data/t1data/lba/L525880/L525880_SB000_uv.MS', 'scripts': '/lofsoft/PiLL/scripts'}
```

**Comment by adrabent** [comment]
If the pipeline runs through it smoothly, I treat this issue as being solved.
