### ISSUE TITLE
Final H5parm_exporter.py step crash (step 17d): 'numpy.float64' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by ajstewart** [lofar-astron/PiLL#3]
The pipeline has crashed right near the end when exporting the tables after the final losoto step. Looks like it's a bug in the edited H5parm_exporter.py script? Let me know if the full log is needed or anything else.

```
2017-02-03 15:01:05 WARNING node.pi3.executable_args.pipeline.h5parm2: /cherrypi/stewart/NCP_Processing/2017-Processing/PiLL-L259185/scripts/H5parm_exporter.py stderr: INFO: Input H5parm filename = /home/stewart/cherrypi/NCP_Processing/2017-Processing/PiLL-L259185/fourth-test-L259185/pipeline/pipeline.h5parm2
DEBUG: Reading from /home/stewart/cherrypi/NCP_Processing/2017-Processing/PiLL-L259185/fourth-test-L259185/pipeline/pipeline.h5parm2.
INFO: Input globaldb/SB filename = /home/stewart/cherrypi/NCP_Processing/2017-Processing/PiLL-L259185/fourth-test-L259185/pipeline/pipeline.globaldbclock
INFO: Solution set name = sol000
INFO: Output globaldb/SB filename = /home/stewart/cherrypi/NCP_Processing/2017-Processing/PiLL-L259185/fourth-test-L259185/pipeline/pipeline.globaldbclock
INFO: Using solution tables: ['amplitudeSmooth000', 'phaseOrig000', 'clock000']
INFO: Found solution types in input parmdb and H5parm: Gain, Clock
INFO: Filling /home/stewart/cherrypi/NCP_Processing/2017-Processing/PiLL-L259185/fourth-test-L259185/pipeline/pipeline.globaldbclock/sol000_instrument-0:
DEBUG: Caching...                                                             |
DEBUG: Caching...
DEBUG: Caching...
Traceback (most recent call last):
  File "/cherrypi/stewart/NCP_Processing/2017-Processing/PiLL-L259185/scripts/H5parm_exporter.py", line 547, in <module>
    val = np.tile( val, np.append([nfreq], np.ones(len(val.shape)) ) )
  File "/mnt/home/stewart/.virtualenvs/PiLL/local/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 881, in tile
    return c.reshape(shape_out)
TypeError: 'numpy.float64' object cannot be interpreted as an index
Closing remaining open files:/home/stewart/cherrypi/NCP_Processing/2017-Processing/PiLL-L259185/fourth-test-L259185/pipeline/pipeline.h5parm2...done

2017-02-03 15:01:07 ERROR   node.pi3.executable_args: Command '/cherrypi/stewart/NCP_Processing/2017-Processing/PiLL-L259185/scripts/H5parm_exporter.py' returned non-zero exit status 1
```

**Comment by adrabent** [comment]
Hmm.. this really looks like a bug in the H5parm_exporter.py.
My modifications are minor and according to your log are working (it takes the right parameters from the parset). I updated the exporter to Francescos github version. You can also tray to run the command manually:

./H5parm_exporter.py -v -c -t "amplitudeSmooth000;phaseOrig000;clock000" pipeline.h5parm2 pipeline.globaldbclock

You can also remove the sol000_instrument-? tables in pipeline.globaldbclock before.

You can also run it with the "original" version of losoto, but then you need to replace the semicolons by commas.

If the problem persists I would contact Francesco de Gasperin as the developer of losoto.

**Comment by ajstewart** [comment]
Seems to be a numpy/losoto compatibility issue - downgrading to numpy v1.11.0 (from v1.12.0) fixed the issue.

So the requirements seem to be numpy>=1.9.0, numpy<=1.11.0.

As this is a losoto error this can be closed.
