### ISSUE TITLE
calibrator-h5parmmerge:  IndexError: list index out of range

### ISSUE THREAD

**Issue by mknapp55** [lofar-astron/PiLL#31]
This error looks a little like #1, but it's at a different step and it has occurred twice at this step with different datasets, so I don't think it's a quirk of the data.

```
2017-07-17 04:57:58 INFO    genericpipeline: Beginning step calibrator-h5parmmerge
2017-07-17 04:57:58 INFO    genericpipeline: Running task: executable_args
2017-07-17 04:57:58 INFO    genericpipeline.executable_args: recipe executable_args started
2017-07-17 04:57:58 INFO    genericpipeline.executable_args: Starting /usr/local/bin/H5parm_merge.py run
2017-07-17 04:57:58 DEBUG   genericpipeline.executable_args: Pipeline start time: 2017-07-14T19:45:32
2017-07-17 04:57:58 ERROR   genericpipeline.executable_args: Exception caught: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/lofarpipe/cuisine/WSRTrecipe.py", line 132, in run
    status = self.go()
  File "/usr/lib/python2.7/dist-packages/lofarpipe/recipes/master/executable_args.py", line 254, in go
    outdata = copy.deepcopy(inputmapfiles[0])
IndexError: list index out of range
```

**Comment by mknapp55** [comment]
I tried changing h5parmmerge.arguments.flags to point to the mapfiles correctly:
```
h5parmmerge.argument.flags                                   =   [-v,listsoltableCD.output.mapfile,listsoltable2.output.mapfile]
```
The result is below.  It found the inputs, which is a step beyond the error above, but it complains that the H5parm file is missing.  Both input and output H5parm files definitely exist and are not empty.
```
2017-07-22 22:41:31 INFO    genericpipeline.executable_args: Starting /usr/local/bin/H5parm_merge.py run
Reading configuration file: /data/scripts/working_L352044/pipeline.cfg
Reading task definition file(s): /usr/share/pipeline/tasks.cfg
2017-07-22 22:41:31 DEBUG   genericpipeline.executable_args: Pipeline start time: 2017-07-22T22:41:20
2017-07-22 22:41:31 INFO    genericpipeline.executable_args: Limiting to 16 simultaneous jobs/node
2017-07-22 22:41:31 DEBUG   genericpipeline.executable_args: Job dispatcher at 128.149.112.159:42791
2017-07-22 22:41:31 INFO    genericpipeline.executable_args: ********************** Remote method is local
2017-07-22 22:41:31 INFO    genericpipeline.executable_args: Waiting for compute threads...
2017-07-22 22:41:31 INFO    genericpipeline.executable_args: Subprocess starting: /bin/sh -c python /usr/lib/python2.7/dist-packages/lofarpipe/recipes/nodes/executable_args.py 0 128.149.112.159 42791 (['/
bin/sh', '-c', 'python /usr/lib/python2.7/dist-packages/lofarpipe/recipes/nodes/executable_args.py 0 128.149.112.159 42791'])
2017-07-22 22:41:31 WARNING genericpipeline.executable_args: /usr/lib/python2.7/dist-packages/lofarpipe/support/utilities.pyc : Using default subprocess module!
2017-07-22 22:41:31 DEBUG   genericpipeline.executable_args: Request for job 0 from ('128.149.112.159', 48330)
2017-07-22 22:41:31 DEBUG   node.jvla.jpl.nasa.gov.executable_args: infile            = /data/scripts/working_L352044/LBA_pipeline_L352044/LBA_pipeline_L352044.calibrator-h5parmCD/:sol000
2017-07-22 22:41:31 DEBUG   node.jvla.jpl.nasa.gov.executable_args: executable        = /usr/local/bin/H5parm_merge.py
2017-07-22 22:41:31 DEBUG   node.jvla.jpl.nasa.gov.executable_args: working directory = /data/scripts/working_L352044/LBA_pipeline_L352044
2017-07-22 22:41:31 DEBUG   node.jvla.jpl.nasa.gov.executable_args: arguments         = ['-v', '/data/scripts/working_L352044/LBA_pipeline_L352044/LBA_pipeline_L352044.calibrator-h5parmCD/:sol000', '/data
/scripts/working_L352044/LBA_pipeline_L352044/LBA_pipeline_L352044.calibrator-h5parm2/:solcd']
2017-07-22 22:41:31 DEBUG   node.jvla.jpl.nasa.gov.executable_args: arg dictionary    = {}
[...]
2017-07-22 22:41:31 WARNING node.jvla.jpl.nasa.gov.executable_args.:sol000: /usr/local/bin/H5parm_merge.py stderr: INFO: H5parm origin = /data/scripts/working_L352044/LBA_pipeline_L352044/LBA_pipeline_L352044.calibrator-h5parmCD/:sol000
INFO: H5parm destination = /data/scripts/working_L352044/LBA_pipeline_L352044/LBA_pipeline_L352044.calibrator-h5parm2/:solcd
CRITICAL: Missing H5parm file.
```

**Comment by adrabent** [comment]
So, both mapfiles point to valid and existing h5parm-sets and both mapfiles have the same length, namely 1?
So, I'll presume it does not except the slash '/' in the command, so I hope this update will properly correct your mapfiles.

**Comment by mknapp55** [comment]
The mapfile names in step h5parmmerge (line 855 in calibrator.parset) were not changed in the update.  Once I changed them manually, the pipeline completed, so your commit fixed the problem with the h5parm files.
